### ISSUE TITLE
Installation using podman

### ISSUE THREAD

**Issue by BenMuthigAixACCT** [tux-evse/iso15118-simulator-rs#3]
Hey,

I'm trying to get the simulator working using podman. While running >>podman build --no-cache -t afb-iso15118 -f Dockerfile , I get following error:
error[E0412]: cannot find type `__BindgenBitfieldUnit` in this scope
  --> afb-librs/src/../capi/_libafb-map.rs:14:46365
...
at STEP "RUN microdnf ..."

Any help would be appreciated.

Kind regards,
Ben

A few additional notes:
- I am using podman version 4.9.3, which for some reason doesn't seem to like heredoc notation, so I've edited the dockerfile to use && \
- The link https://download.redpesk.bzh/redpesk-lts/batz-2.0-update/packages/middleware/x86_64/os/Packages/a/afb-ui-devtools-1.0.4-2.redpesk.devtools.rpbatz.noarch.rpm used in the dockerfile 404s. I've changed it to use https://download.redpesk.bzh/redpesk-lts/batz-2.0-update/packages/middleware/x86_64/os/Packages/a/afb-ui-devtools-1.0.5-2.redpesk.devtools.rpbatz.noarch.rpm instead

**Comment by fulup-bzh** [comment]
To be honest with you, we did not retry podman since a while. Unfortunately is OCI version is very convenient to run pcap-iso15118 to create scenario from tcpdump trace, running the simulator imposes to either get access to low level Ethernet interface or to create a virtual network in the container, which is not as simple as it should.

For a quick-start we recommend to start with binary distribution, that we maintain for major Linux distributions. Follow https://github.com/tux-evse/iso15118-simulator-rs/blob/main/README.md#quick-start-simulating-both-evseevcc

@ronan22 could you check devtools URL and replace it with a valid one.

@BenMuthigAixACCT the error you have is simple, but current script only provide ```pcap-iso15118``` command. Building the full simulator a in container may require more time and running it very unfriendly options.

**Comment by BenMuthigAixACCT** [comment]
Thanks for the response. I have tried using the binary distribution as described in the quick-start guide but run into the same problem as bananen-republik in issue #2.

**Comment by ronan22** [comment]
Now, you can test the iso15118 binder with podman, doc:
https://github.com/tux-evse/iso15118-simulator-rs/blob/main/README.md#test-the-binder-with-podman

If you have any kind of trouble with the podman test, please contact us.
