### ISSUE TITLE
Wrong parsed transfer mode in EXI decoder

### ISSUE THREAD

**Issue by bananen-republik** [tux-evse/iso15118-simulator-rs#4]
Hi everyone,

in the EXI decoder, there must be a typo decoding the "transfers" in "ServiceDiscoveryResp".
`ac_three_phase` is parsed as `ac_tree_phase`which then results in an error:

`3 : {
  "jtype": "afb-event",
  "event": "iso15118-injector/etron-20230307:1:0",
  "data": {
    "uid": "pkg:78",
    "verb": "iso2:service_discovery_req",
    "error": {
      "uid": "transfers:1",
      "info": "jsonc-match invalid value received:\"ac_tree_phase\" expected:\"ac_three_phase\""
    }
  }
}`

Best regards

**Comment by fulup-bzh** [comment]
Yes, the error is on my side. I'm investigating should be easy to fix.

**Comment by fulup-bzh** [comment]
@ronan22 I fixed 'EngyTransfertMode::AcThreePhase' status name from which Json label is derived in iso-encoder-rs. Could your please update binary packages.
@bananen-republik did you generate your scenario by hand ? 
Using 'pcap-iso15118' tool you should have ended up with 'ac_tree_phase' as expected label.

Conclusion: If you run from Rust source a simple pull on encoder-rs repo should be enough. Otherwise replace 'ac_three_phase' with ' ac_tree_phase' in scenario. This until Ronan update binary repositories.

**Comment by fulup-bzh** [comment]
This should be fixed with last version. Please let us known if you still have the issue.

**Comment by fulup-bzh** [comment]
This should be fixed with last version. Please let us known if you still have the issue.
